# Generated by Django 4.0.4 on 2022-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('message', models.TextField()),
                ('isDone', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
