# Generated by Django 4.0.4 on 2022-04-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todoList',
            new_name='Todo',
        ),
    ]
